image: 'docker:latest'

services:
  - docker:dind

variables:
  CGO_ENABLED: "0"
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - apk update
  - apk add make python py-pip
  - pip install docker-compose

stages:
  - test

go_test:
  stage: test
  script:
    - make -s test
