image: 'golang:latest'

before_script:
  - 'export GIT_SSL_NO_VERIFY=true'

stages:
  - test
  - build

go_test:
  stage: test
  script:
    - go get github.com/rakyll/magicmime
    - go fmt
    - go test

go_build:
  stage: build
  script: go build
