language: go

go:
  - "1.11.x"

before_install:
  - sudo apt-get install -y libmagic-dev golang-glide gcc make
  - wget "https://github.com/Masterminds/glide/releases/download/0.13.2/glide-0.13.2-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-0.13.2-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"

script:
  - make test
