stages:
  - test
  - name: publish
    if: branch = master AND type = push
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      before_install:
        - sudo apt-get install -y gcc make libmagic-dev
      script:
        - make test
      language: go
      go: 1.11.x
      env:
        - GO111MODULE=on
    - stage: publish
      before_script:
        - echo $GCP_SERVICE_ACCOUNT | base64 --decode > keyfile.json
        - cat keyfile.json | docker login -u _json_key --password-stdin https://gcr.io
        - cat resty/nginx.conf.base > resty/nginx.conf
        - sed 's;__PASTE_CLICK_UPSTREAM__;http://paste-click.paste-click.svc.cluster.local:8001;' < resty/paste.click.conf.base > resty/paste.click.conf
      script:
        - docker build -t gcr.io/$GCP_PROJECT_ID/paste-click:$TRAVIS_COMMIT .
        - docker tag gcr.io/$GCP_PROJECT_ID/paste-click:$TRAVIS_COMMIT gcr.io/$GCP_PROJECT_ID/paste-click:latest
        - docker push gcr.io/$GCP_PROJECT_ID/paste-click:$TRAVIS_COMMIT
        - docker push gcr.io/$GCP_PROJECT_ID/paste-click:latest
        - docker build -t gcr.io/$GCP_PROJECT_ID/openresty-paste-click:$TRAVIS_COMMIT -f Dockerfile.openresty .
        - docker tag gcr.io/$GCP_PROJECT_ID/openresty-paste-click:$TRAVIS_COMMIT gcr.io/$GCP_PROJECT_ID/openresty-paste-click:latest
        - docker push gcr.io/$GCP_PROJECT_ID/openresty-paste-click:$TRAVIS_COMMIT
        - docker push gcr.io/$GCP_PROJECT_ID/openresty-paste-click:latest
      services:
        - docker
    - stage: deploy
      install:
        - sudo apt-get install -y apt-transport-https
        - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        - sudo apt-get update
        - sudo apt-get install -y kubectl
      script:
        - ./deploy.sh
