version: '3.1'
services:
  frontend:
    image: openresty/openresty:alpine
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - content:/www/paste.click/
      - frontend_logs:/var/log/nginx
      - ./assets/index.html:/www/paste.click/index.html
      - ./assets/s:/www/paste.click/s
      - ./assets/up:/www/paste.click/up
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./conf/paste.click.conf:/usr/local/openresty/nginx/conf/sites-enabled/paste.click.conf:ro
      - ./conf/lua:/usr/local/openresty/nginx/conf/lua
      - ./conf/ssl:/etc/ssl/nginx:ro
    networks:
      - backend
    depends_on:
      - backend
  backend:
    image: ncatelli/golang:1.9.2-libmagic
    build:
      context: ./
    command: bash -c "go install gitlab.packetfire.org/Tiksi/paste-click && ./bin/paste-click"
    environment:
      GOPATH: '/go'
      PASTE_CLICK_BINDADDR: '0.0.0.0'
    volumes:
      - .:/go/src/gitlab.packetfire.org/Tiksi/paste-click
      - ./vendor:/go/src/gitlab.packetfire.org/Tiksi/paste-click/vendor
      - content:/www/paste.click/
    networks:
      - backend
volumes:
  content:
  frontend_logs:
networks:
  backend:
