version: '3.1'
services:
  frontend:
    image: packetfire/openresty-pasteclick
    build:
      context: ./
      dockerfile: Dockerfile.openresty
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - content:/www/paste.click/
      - ./assets/index.html:/www/paste.click/index.html
      - ./assets/s:/www/paste.click/s
      - ./assets/up:/www/paste.click/up
      - ./resty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./resty/paste.click.conf:/usr/local/openresty/nginx/conf/sites-enabled/paste.click.conf:ro
      - ./resty/ssl:/etc/ssl/nginx:ro
    networks:
      - backend
    depends_on:
      - backend
  backend:
    image: packetfire/pasteclick
    build:
      context: ./
    command: /opt/bin/paste-click
    environment:
      ADDR: ':8001'
      STORAGE_DRIVER: 'fs'
      STORE_FS_BASE_PATH: "/www/paste.click/"
    ports:
      - 8001:8001
    volumes:
      - content:/www/paste.click/
    networks:
      - backend
volumes:
  content:
networks:
  backend:
