version: '3.1'
services:
  frontend:
    image: packetfire/openresty-pasteclick
    build:
      context: ./
      dockerfile: Dockerfile.openresty
    environment:
      PASTE_CLICK_UPSTREAM: "http://backend:8001"
      PASTE_CLICK_FRONTEND_BUCKET: none
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - proxy_cache:/data/nginx/cache
      - ./resty/ssl:/etc/ssl/nginx:ro
    networks:
      - backend
    depends_on:
      - backend
  backend:
    image: packetfire/pasteclick
    build:
      context: ./
    command: /opt/bin/paste-click
    environment:
      ADDR: ':8001'
      STORAGE_DRIVER: 'fs'
      STORE_FS_BASE_PATH: "/www/paste.click/objects/"
      SITE_NAME: "localhost:8080"
    ports:
      - 8001:8001
    volumes:
      - content:/www/paste.click/objects/
    networks:
      - backend
volumes:
  content:
  proxy_cache:
networks:
  backend:
